### ISSUE TITLE
the autocode-cli should have compiled into javascript before publishing it to the npm registry

### ISSUE THREAD

**Issue by adoyle-h** [crystal/autocode#19]
It is too slow when run `autocode` command. Because everytime it compiles the coffeescript in runtime, which costs lots of time.
You should have compiled it into javascript before publishing it to the npm registry.

**Comment by adoyle-h** [comment]
It seems that the `lib/` folder is the compiled result from `src/`, but `cli/ascii.coffee` and `cli/help.coffee` need to be compiled.
I suggest removing this line `require('coffee-script').register();` from `bin/autocode`. Write the cli files in javascript.

**Comment by ctate** [comment]
Fixed at adb0a9c66c4eee7ae7221bc7860f5634206c719f. Added `cli/src/` and `cli/lib/` to compile to JS for CLI. Removed `require('coffee-script').register()` and added `.npmignore` so `cli/src/` and `src/` aren't published to npm.

Thank you so much for your help and support!

**Comment by adoyle-h** [comment]
You are welcome. I think the project will be a great work. Well done  :+1:
