### ISSUE TITLE
0.5.1 checksum change

### ISSUE THREAD

**Issue by DomT4** [crystal/autocode#9]
The `v0.5.1` [tag](https://github.com/crystal/autocode-js/releases/tag/v0.5.1)'s SHA256 checksum broke at some point recently. Not completely sure when, but confirmed that it matched:
```
6c022ad59a10cec58856dba858a030b745333909108c08bd326c20ac0cb144fb
```
Until at least August 18th. The checksum now seems to be:
```
529c00971e066dec246f9e1e1c174720c4f29f2a2185dea674a3d052c5426570
```

Was there some intentional retagging/etc upstream here? Originally raised at Homebrew in https://github.com/Homebrew/homebrew/issues/44372.

**Comment by ctate** [comment]
@DomT4 We migrated from crystal/crystal to crystal/autocode over the weekend and were under the assumption that GitHub would redirect everything. We submitted a PR to rename `crystal` as `autocode`: https://github.com/Homebrew/homebrew/pull/44417
